"""add bookmarks table

Revision ID: 00e469a985ef
Revises: 0b59137a5005
Create Date: 2026-03-13 09:57:30.112922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e469a985ef'
down_revision: Union[str, Sequence[str], None] = '0b59137a5005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmarks',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('target_hash', sa.BIGINT(), nullable=False),
    sa.Column('fen', sa.String(length=200), nullable=False),
    sa.Column('moves', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.Column('match_side', sa.String(length=10), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    # ### end Alembic commands ###
