"""add is_computer_game to games

Revision ID: 0b59137a5005
Revises: d809d42c7521
Create Date: 2026-03-12 21:23:51.596459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b59137a5005'
down_revision: Union[str, Sequence[str], None] = 'd809d42c7521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('is_computer_game', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'is_computer_game')
    # ### end Alembic commands ###
