"""phase 167 bot_game_settings table

Revision ID: a07ccca76092
Revises: 12d3df9c5373
Create Date: 2026-07-11 18:52:07.628538+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a07ccca76092"
down_revision: Union[str, Sequence[str], None] = "12d3df9c5373"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_game_settings",
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("nominal_elo", sa.SmallInteger(), nullable=False),
        sa.Column("play_style_blend", sa.REAL(), nullable=False),
        sa.Column("tc_preset", sa.Text(), nullable=False),
        sa.Column("rating_source", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "rating_source IN ('lichess', 'chesscom', 'blended')",
            name="ck_bot_game_settings_rating_source",
        ),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("game_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bot_game_settings")
    # ### end Alembic commands ###
