"""phase 174 game_best_moves table

Revision ID: 903b54b77161
Revises: a07ccca76092
Create Date: 2026-07-16 12:52:31.195467+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "903b54b77161"
down_revision: Union[str, Sequence[str], None] = "a07ccca76092"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_best_moves",
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("ply", sa.SmallInteger(), nullable=False),
        sa.Column("maia_prob", sa.REAL(), nullable=False),
        sa.Column("best_cp", sa.SmallInteger(), nullable=True),
        sa.Column("best_mate", sa.SmallInteger(), nullable=True),
        sa.Column("second_cp", sa.SmallInteger(), nullable=True),
        sa.Column("second_mate", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("game_id", "ply"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("game_best_moves")
    # ### end Alembic commands ###
