"""add is_flipped to bookmarks

Revision ID: f10322cb88b3
Revises: 00e469a985ef
Create Date: 2026-03-13 12:36:05.106025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f10322cb88b3'
down_revision: Union[str, Sequence[str], None] = '00e469a985ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('is_flipped', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmarks', 'is_flipped')
    # ### end Alembic commands ###
