"""phase 122 feedback rating column

Revision ID: 7d5a4aa09a47
Revises: 60160718b3b3
Create Date: 2026-06-15 20:24:40.619011+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d5a4aa09a47"
down_revision: Union[str, Sequence[str], None] = "60160718b3b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Swap the feedback.sentiment string column (3-point sentiment) for a numeric
    1-5 star rating column. Both this and the table-creating revision 60160718b3b3
    are Phase 122 and unreleased, so they can be squashed into a single migration
    before this milestone ships. Hand-written (not autogenerated) to avoid pulling
    in unrelated partial-index drift from Phases 116/119 (same reason 60160718b3b3
    is scoped to only the feedback table).
    """
    op.drop_column("feedback", "sentiment")
    op.add_column("feedback", sa.Column("rating", sa.SmallInteger(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("feedback", "rating")
    op.add_column("feedback", sa.Column("sentiment", sa.String(length=16), nullable=True))
