"""add position metadata columns

Revision ID: 38239eef59a8
Revises: b5b8170c0f72
Create Date: 2026-03-23 21:32:17.119812+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38239eef59a8'
down_revision: Union[str, Sequence[str], None] = 'b5b8170c0f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_positions', sa.Column('game_phase', sa.String(length=12), nullable=True))
    op.add_column('game_positions', sa.Column('material_signature', sa.String(length=40), nullable=True))
    op.add_column('game_positions', sa.Column('material_imbalance', sa.Integer(), nullable=True))
    op.add_column('game_positions', sa.Column('endgame_class', sa.String(length=12), nullable=True))
    op.add_column('game_positions', sa.Column('has_bishop_pair_white', sa.Boolean(), nullable=True))
    op.add_column('game_positions', sa.Column('has_bishop_pair_black', sa.Boolean(), nullable=True))
    op.add_column('game_positions', sa.Column('has_opposite_color_bishops', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_positions', 'has_opposite_color_bishops')
    op.drop_column('game_positions', 'has_bishop_pair_black')
    op.drop_column('game_positions', 'has_bishop_pair_white')
    op.drop_column('game_positions', 'endgame_class')
    op.drop_column('game_positions', 'material_imbalance')
    op.drop_column('game_positions', 'material_signature')
    op.drop_column('game_positions', 'game_phase')
    # ### end Alembic commands ###
