"""add move_count to games and usernames to users

Revision ID: f009f3b41e8e
Revises: 7eb7ce83cdb9
Create Date: 2026-03-14 16:42:03.837592

"""
import logging
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

logger = logging.getLogger(__name__)

# revision identifiers, used by Alembic.
revision: str = 'f009f3b41e8e'
down_revision: Union[str, Sequence[str], None] = '7eb7ce83cdb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_BATCH_SIZE = 500


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('move_count', sa.BIGINT(), nullable=True))
    op.add_column('users', sa.Column('chess_com_username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('lichess_username', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lichess_username')
    op.drop_column('users', 'chess_com_username')
    op.drop_column('games', 'move_count')
    # ### end Alembic commands ###
