"""add worker_heartbeats table

Revision ID: b4ea823c85be
Revises: df8d4f5bc37b
Create Date: 2026-07-04 11:20:59.398562+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ea823c85be'
down_revision: Union[str, Sequence[str], None] = 'df8d4f5bc37b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_heartbeats',
    sa.Column('worker_id', sa.String(length=16), nullable=False),
    sa.Column('last_ip', sa.Text(), nullable=True, comment='Operator-owned worker machine IP (local box + Hetzner), not an end-user IP — negligible GDPR surface (D-06).'),
    sa.Column('sf_version', sa.String(length=50), nullable=True),
    sa.Column('worker_schema_version', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submit_count', sa.BigInteger(), nullable=False),
    sa.Column('evals_submitted', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('worker_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_heartbeats')
    # ### end Alembic commands ###
