"""drop redundant user-relative columns

Revision ID: 697d7b8842d2
Revises: 1c4985e5016a
Create Date: 2026-03-14 19:43:22.599840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697d7b8842d2'
down_revision: Union[str, Sequence[str], None] = '1c4985e5016a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'opponent_rating')
    op.drop_column('games', 'user_rating')
    op.drop_column('games', 'opponent_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('opponent_username', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('user_rating', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('opponent_rating', sa.BIGINT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
