"""add white black username rating columns

Revision ID: 1c4985e5016a
Revises: f009f3b41e8e
Create Date: 2026-03-14 18:12:58.037161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4985e5016a'
down_revision: Union[str, Sequence[str], None] = 'f009f3b41e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('white_username', sa.String(length=100), nullable=True))
    op.add_column('games', sa.Column('black_username', sa.String(length=100), nullable=True))
    op.add_column('games', sa.Column('white_rating', sa.BIGINT(), nullable=True))
    op.add_column('games', sa.Column('black_rating', sa.BIGINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'black_rating')
    op.drop_column('games', 'white_rating')
    op.drop_column('games', 'black_username')
    op.drop_column('games', 'white_username')
    # ### end Alembic commands ###
