"""add move_san to game_positions

Revision ID: d861bce078a5
Revises: 697d7b8842d2
Create Date: 2026-03-16 18:07:37.827617+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd861bce078a5'
down_revision: Union[str, Sequence[str], None] = '697d7b8842d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_positions', sa.Column('move_san', sa.String(length=10), nullable=True))
    op.create_index('ix_gp_user_full_hash_move_san', 'game_positions', ['user_id', 'full_hash', 'move_san'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gp_user_full_hash_move_san', table_name='game_positions')
    op.drop_column('game_positions', 'move_san')
    # ### end Alembic commands ###
