"""add engine analysis columns

Revision ID: cf839d2edbf8
Revises: 8b6149400d29
Create Date: 2026-03-25 21:32:50.515641+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf839d2edbf8'
down_revision: Union[str, Sequence[str], None] = '8b6149400d29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_positions', sa.Column('eval_cp', sa.SmallInteger(), nullable=True))
    op.add_column('game_positions', sa.Column('eval_mate', sa.SmallInteger(), nullable=True))
    op.alter_column('game_positions', 'clock_seconds',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=24),
               existing_nullable=True)
    op.add_column('games', sa.Column('white_accuracy', sa.Float(precision=24), nullable=True))
    op.add_column('games', sa.Column('black_accuracy', sa.Float(precision=24), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'black_accuracy')
    op.drop_column('games', 'white_accuracy')
    op.alter_column('game_positions', 'clock_seconds',
               existing_type=sa.Float(precision=24),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('game_positions', 'eval_mate')
    op.drop_column('game_positions', 'eval_cp')
    # ### end Alembic commands ###
