"""replace game_phase and bishop columns with material_count

Revision ID: 1fac8294077e
Revises: 38239eef59a8
Create Date: 2026-03-24 18:34:35.127880+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fac8294077e'
down_revision: Union[str, Sequence[str], None] = '38239eef59a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_positions', sa.Column('material_count', sa.SmallInteger(), nullable=True))
    op.alter_column('game_positions', 'material_imbalance',
               existing_type=sa.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=True)
    op.drop_column('game_positions', 'endgame_class')
    op.drop_column('game_positions', 'has_bishop_pair_black')
    op.drop_column('game_positions', 'game_phase')
    op.drop_column('game_positions', 'has_bishop_pair_white')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_positions', sa.Column('has_bishop_pair_white', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('game_positions', sa.Column('game_phase', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.add_column('game_positions', sa.Column('has_bishop_pair_black', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('game_positions', sa.Column('endgame_class', sa.VARCHAR(length=12), autoincrement=False, nullable=True))
    op.alter_column('game_positions', 'material_imbalance',
               existing_type=sa.SmallInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('game_positions', 'material_count')
    # ### end Alembic commands ###
