"""Phase 117: eval_jobs queue table, best_move/pv columns, lichess_evals_at backfill.

Phase 117 EVAL-04, EVAL-06, QUEUE-01, QUEUE-06 / D-117-01, D-117-02, D-117-06,
D-117-10, D-117-12.

Adds:
  - game_positions.best_move VARCHAR(5) nullable — UCI PV[0] for every evaluated
    position (D-117-01/03). Opening-region transplanted via full_hash dedup.
  - game_positions.pv TEXT nullable — ~12-ply UCI refutation line at flaw-adjacent
    positions only (ply = flaw_ply + 1, D-117-02).
  - games.lichess_evals_at TIMESTAMPTZ nullable — provenance: set ONLY when lichess
    %evals are ingested at import (D-117-06). WR-02 discriminator replaces the
    white_blunders IS NULL gate (D-117-07).
  - games.full_pv_completed_at TIMESTAMPTZ nullable — parallel to full_evals_completed_at;
    marks when best_move is captured for all plies (D-117-12).
  - ix_games_full_pv_pending partial index on games(id) WHERE full_pv_completed_at IS NULL.
  - eval_jobs table (QUEUE-01/06): tier-ordered priority queue with SELECT FOR UPDATE
    SKIP LOCKED lease semantics. Columns: id, tier, user_id (FK CASCADE), game_id (FK
    CASCADE), status, leased_by, lease_expiry, created_at, completed_at.
  - uq_eval_jobs_game_active partial unique index: one active (pending/leased) job
    per game (RESEARCH Open Question 1 / Pitfall 6).
  - ix_eval_jobs_pick: (tier, user_id, created_at) WHERE status='pending'.
  - ix_eval_jobs_leased: (lease_expiry) WHERE status='leased'.
  - D-117-10 one-time backfill: SET lichess_evals_at = COALESCE(imported_at, NOW())
    WHERE white_blunders IS NOT NULL. Runs LAST (Pitfall 5) after the column exists.
    games table is ~558k rows (not 44M) — no batching needed. Irreversible by design
    (downgrade does NOT unset lichess_evals_at values set before migration).

NOTE: Adding nullable columns to PostgreSQL 18 is a pure catalog update — no table
rewrite, no extended lock on the 44.4M-row game_positions table (assumption A1,
confirmed for PG 11+). Safe to run inline at deploy time via deploy/entrypoint.sh.

Revision ID: <autogenerated — see revision variable below>
Revises: 20260612120000 (Phase 116 full_evals_completed_at)
Create Date: 2026-06-13 12:00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260613120000"
down_revision: Union[str, None] = "20260612120000"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add columns, eval_jobs table, indexes, then D-117-10 backfill (Pitfall 5: backfill last).

    Step 1: game_positions nullable columns (instant metadata op — no table rewrite).
    Step 2: games nullable columns (instant).
    Step 3: ix_games_full_pv_pending partial index (mirrors ix_games_full_evals_pending).
    Step 4: eval_jobs table + three partial indexes (QUEUE-01/06).
    Step 5: D-117-10 lichess_evals_at backfill (must run after column + indexes exist,
            before any drain traffic — guaranteed by entrypoint.sh migration ordering).
    """
    # Step 1: game_positions nullable columns (eval output, no table rewrite)
    op.add_column(
        "game_positions",
        sa.Column("best_move", sa.String(5), nullable=True),
    )
    op.add_column(
        "game_positions",
        sa.Column("pv", sa.Text(), nullable=True),
    )

    # Step 2: games nullable columns
    op.add_column(
        "games",
        sa.Column("lichess_evals_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "games",
        sa.Column("full_pv_completed_at", sa.DateTime(timezone=True), nullable=True),
    )

    # Step 3: partial index for PV-pending pick (D-117-12, mirrors ix_games_full_evals_pending)
    op.create_index(
        "ix_games_full_pv_pending",
        "games",
        ["id"],
        unique=False,
        postgresql_where="full_pv_completed_at IS NULL",
    )

    # Step 4: eval_jobs queue/lease table (QUEUE-01, QUEUE-06)
    op.create_table(
        "eval_jobs",
        sa.Column("id", sa.BigInteger(), nullable=False, autoincrement=True),
        sa.Column("tier", sa.SmallInteger(), nullable=False),
        sa.Column(
            "user_id",
            sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "game_id",
            sa.Integer(),
            sa.ForeignKey("games.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(20),
            nullable=False,
            server_default="pending",
        ),
        sa.Column("leased_by", sa.String(100), nullable=True),
        sa.Column("lease_expiry", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name="eval_jobs_pkey"),
    )
    # Partial unique: at most one active (pending or leased) job per game.
    # Completed/failed rows don't block re-enqueue (RESEARCH Open Question 1).
    op.create_index(
        "uq_eval_jobs_game_active",
        "eval_jobs",
        ["game_id"],
        unique=True,
        postgresql_where="status IN ('pending', 'leased')",
    )
    # Tier-ordered pick index covering pending status (QUEUE-01/02)
    op.create_index(
        "ix_eval_jobs_pick",
        "eval_jobs",
        ["tier", "user_id", "created_at"],
        unique=False,
        postgresql_where="status = 'pending'",
    )
    # Lease-expiry sweep index for requeue-on-expiry
    op.create_index(
        "ix_eval_jobs_leased",
        "eval_jobs",
        ["lease_expiry"],
        unique=False,
        postgresql_where="status = 'leased'",
    )

    # Step 5: D-117-10 one-time lichess_evals_at backfill.
    # Sets lichess_evals_at for every existing game where white_blunders IS NOT NULL
    # (today that population is exactly the lichess-analyzed set). Captures historical
    # provenance before engine-filled oracle counts blur the white_blunders signal.
    # games table is ~558k rows — no batching needed (not the 44M game_positions table).
    # COALESCE(imported_at, NOW()) mirrors the Phase 116 full_evals_completed_at backfill.
    op.execute("""
        UPDATE games
        SET lichess_evals_at = COALESCE(imported_at, NOW())
        WHERE white_blunders IS NOT NULL
          AND lichess_evals_at IS NULL
    """)


def downgrade() -> None:
    """Reverse in opposite order: eval_jobs indexes + table, games index, columns.

    D-117-10 backfill is NOT reversed — the backfill SET is irreversible by design.
    Downgrade removes only the schema additions; any lichess_evals_at values set by
    the backfill are gone once the column is dropped (acceptable — the column itself
    is dropped, so no stale provenance data lingers).
    """
    # Drop eval_jobs indexes before dropping the table
    op.drop_index(
        "ix_eval_jobs_leased",
        table_name="eval_jobs",
        postgresql_where="status = 'leased'",
    )
    op.drop_index(
        "ix_eval_jobs_pick",
        table_name="eval_jobs",
        postgresql_where="status = 'pending'",
    )
    op.drop_index(
        "uq_eval_jobs_game_active",
        table_name="eval_jobs",
        postgresql_where="status IN ('pending', 'leased')",
    )
    op.drop_table("eval_jobs")

    # Drop games partial index before dropping the column it references
    op.drop_index(
        "ix_games_full_pv_pending",
        table_name="games",
        postgresql_where="full_pv_completed_at IS NULL",
    )

    # Drop games columns
    op.drop_column("games", "full_pv_completed_at")
    op.drop_column("games", "lichess_evals_at")

    # Drop game_positions columns
    op.drop_column("game_positions", "pv")
    op.drop_column("game_positions", "best_move")
