"""make game unique constraint per user

Revision ID: 9549c5e62259
Revises: f3c8c11c64c9
Create Date: 2026-03-20 16:02:54.123976+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9549c5e62259'
down_revision: Union[str, Sequence[str], None] = 'f3c8c11c64c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_games_platform_game_id'), 'games', type_='unique')
    op.create_unique_constraint('uq_games_user_platform_game_id', 'games', ['user_id', 'platform', 'platform_game_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_games_user_platform_game_id', 'games', type_='unique')
    op.create_unique_constraint(op.f('uq_games_platform_game_id'), 'games', ['platform', 'platform_game_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
