"""add is_guest to users

Revision ID: 68879c51818c
Revises: adfafb71bacc
Create Date: 2026-04-06 06:55:27.229555+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68879c51818c'
down_revision: Union[str, Sequence[str], None] = 'adfafb71bacc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_positions', 'clock_seconds',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=24),
               existing_nullable=True)
    op.alter_column('games', 'white_accuracy',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=24),
               existing_nullable=True)
    op.alter_column('games', 'black_accuracy',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=24),
               existing_nullable=True)
    op.add_column('users', sa.Column('is_guest', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_guest')
    op.alter_column('games', 'black_accuracy',
               existing_type=sa.Float(precision=24),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('games', 'white_accuracy',
               existing_type=sa.Float(precision=24),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('game_positions', 'clock_seconds',
               existing_type=sa.Float(precision=24),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
