"""add tactic_depth to game_flaws

Revision ID: 9be5294cfe3c
Revises: 20260617_120000_phase_124
Create Date: 2026-06-19 13:44:42.940175+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9be5294cfe3c'
down_revision: Union[str, Sequence[str], None] = '20260617_120000_phase_124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_flaws', sa.Column('tactic_depth', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_flaws', 'tactic_depth')
    # ### end Alembic commands ###
