"""add pv_lines blobs to game_flaws

Revision ID: 0b6ac7a4b59a
Revises: c4d4588ed2b8
Create Date: 2026-06-29 18:54:59.171700+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b6ac7a4b59a'
down_revision: Union[str, Sequence[str], None] = 'c4d4588ed2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_flaws', sa.Column('allowed_pv_lines', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('game_flaws', sa.Column('missed_pv_lines', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_flaws', 'missed_pv_lines')
    op.drop_column('game_flaws', 'allowed_pv_lines')
    # ### end Alembic commands ###
