"""add move_count to games and usernames to users

Revision ID: f009f3b41e8e
Revises: 7eb7ce83cdb9
Create Date: 2026-03-14 16:42:03.837592

"""
import io
import logging
from typing import Sequence, Union

import chess.pgn
from alembic import op
import sqlalchemy as sa

logger = logging.getLogger(__name__)

# revision identifiers, used by Alembic.
revision: str = 'f009f3b41e8e'
down_revision: Union[str, Sequence[str], None] = '7eb7ce83cdb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_BATCH_SIZE = 500


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('move_count', sa.BIGINT(), nullable=True))
    op.add_column('users', sa.Column('chess_com_username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('lichess_username', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###

    # --- Data migration: backfill move_count for existing games ---
    bind = op.get_bind()
    games_table = sa.table(
        'games',
        sa.column('id', sa.Integer),
        sa.column('pgn', sa.Text),
        sa.column('move_count', sa.Integer),
    )

    offset = 0
    while True:
        rows = bind.execute(
            sa.select(games_table.c.id, games_table.c.pgn)
            .where(games_table.c.move_count.is_(None))
            .where(games_table.c.pgn.isnot(None))
            .order_by(games_table.c.id)
            .limit(_BATCH_SIZE)
            .offset(offset)
        ).fetchall()

        if not rows:
            break

        for game_id, pgn in rows:
            try:
                game_obj = chess.pgn.read_game(io.StringIO(pgn))
                if game_obj is None:
                    continue
                ply_count = len(list(game_obj.mainline_moves()))
                move_count = (ply_count + 1) // 2
                bind.execute(
                    sa.update(games_table)
                    .where(games_table.c.id == game_id)
                    .values(move_count=move_count)
                )
            except Exception:
                logger.warning("Failed to backfill move_count for game_id=%s, skipping", game_id)
                continue

        offset += _BATCH_SIZE


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lichess_username')
    op.drop_column('users', 'chess_com_username')
    op.drop_column('games', 'move_count')
    # ### end Alembic commands ###
