"""add clock_seconds termination columns

Revision ID: 6dc12353580e
Revises: 16ca6995d5cc
Create Date: 2026-03-18 19:36:52.051114+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc12353580e'
down_revision: Union[str, Sequence[str], None] = '16ca6995d5cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_positions', sa.Column('clock_seconds', sa.Float(), nullable=True))
    op.add_column('games', sa.Column('termination_raw', sa.String(length=50), nullable=True))
    op.add_column('games', sa.Column('termination', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'termination')
    op.drop_column('games', 'termination_raw')
    op.drop_column('game_positions', 'clock_seconds')
    # ### end Alembic commands ###
