"""quick qte users import retention facts

Revision ID: feab8324235d
Revises: c3a9e1f70003
Create Date: 2026-09-17 17:28:19.507929+00:00

QTE-01..04: adds three retained-fact columns to `users` --
`first_import_started_at`, `lifetime_games_imported`, `games_purged_at` --
that deliberately SURVIVE the games/import_jobs purge performed by
guest_cleanup_service._purge_guest (30-day guest inactivity sweep) and
DELETE /api/games (D-05, Phase 187). Both purge paths intentionally delete
`games` and `import_jobs` rows while keeping the `users` row, so without a
retained fact the Activity dashboard cannot tell "never imported" apart
from "imported, then purged" and undercounts activation.

Backfill (two op.execute statements, after the add_columns):

(a) per-user aggregate from `import_jobs`: `lifetime_games_imported` becomes
    COALESCE(SUM(games_imported), 0) and `first_import_started_at` becomes
    MIN(started_at), grouped by user_id. Users with no jobs keep the 0 / NULL
    defaults.

(b) purge estimate: `games_purged_at` is set to `users.last_activity` for
    rows where a platform username is set (chess_com_username OR
    lichess_username) AND no `import_jobs` row exists. This is an ESTIMATE
    -- the true purge timestamp is unrecoverable -- and it covers BOTH the
    guest-cleanup population and the DELETE /games population, so registered
    users are affected too. A row whose `last_activity` is NULL stays NULL
    here and is therefore NOT treated as purged by the dashboard queries: an
    accepted, documented residual, since `last_activity` is the only
    timestamp available to stand in for the real purge time.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feab8324235d'
down_revision: Union[str, Sequence[str], None] = 'c3a9e1f70003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_import_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('lifetime_games_imported', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('games_purged_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # Backfill (a): per-user lifetime import totals and first-import timestamp
    # from the surviving import_jobs rows. Users with no jobs keep the
    # 0 / NULL column defaults set above.
    op.execute(
        """
        UPDATE users u
        SET lifetime_games_imported = agg.total_games,
            first_import_started_at = agg.first_started_at
        FROM (
            SELECT user_id,
                   COALESCE(SUM(games_imported), 0) AS total_games,
                   MIN(started_at) AS first_started_at
            FROM import_jobs
            GROUP BY user_id
        ) AS agg
        WHERE u.id = agg.user_id
        """
    )

    # Backfill (b): ESTIMATE `games_purged_at` for users who have a platform
    # username set (so they clearly imported at some point) but no surviving
    # import_jobs row (so their history was purged, either by the guest
    # 30-day cleanup or DELETE /api/games). The true purge timestamp is
    # unrecoverable, so `last_activity` -- the only timestamp we still have --
    # stands in as the estimate. This covers BOTH the guest-cleanup
    # population and the DELETE /games population; registered users are
    # affected too. Rows with a NULL `last_activity` stay NULL here and are
    # therefore NOT treated as purged by the dashboard queries -- an
    # accepted, documented residual.
    op.execute(
        """
        UPDATE users u
        SET games_purged_at = u.last_activity
        WHERE (u.chess_com_username IS NOT NULL OR u.lichess_username IS NOT NULL)
          AND NOT EXISTS (
              SELECT 1 FROM import_jobs j WHERE j.user_id = u.id
          )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'games_purged_at')
    op.drop_column('users', 'lifetime_games_imported')
    op.drop_column('users', 'first_import_started_at')
    # ### end Alembic commands ###
