"""initial schema

Revision ID: dcef507678d8
Revises: 
Create Date: 2026-03-11 13:31:23.972515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcef507678d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('platform_game_id', sa.String(length=100), nullable=False),
    sa.Column('platform_url', sa.String(length=500), nullable=True),
    sa.Column('pgn', sa.Text(), nullable=False),
    sa.Column('variant', sa.String(length=50), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=False),
    sa.Column('user_color', sa.String(length=5), nullable=False),
    sa.Column('time_control_str', sa.String(length=50), nullable=True),
    sa.Column('time_control_bucket', sa.String(length=20), nullable=True),
    sa.Column('time_control_seconds', sa.BIGINT(), nullable=True),
    sa.Column('rated', sa.Boolean(), nullable=False),
    sa.Column('opponent_username', sa.String(length=100), nullable=True),
    sa.Column('opponent_rating', sa.BIGINT(), nullable=True),
    sa.Column('user_rating', sa.BIGINT(), nullable=True),
    sa.Column('opening_name', sa.String(length=200), nullable=True),
    sa.Column('opening_eco', sa.String(length=10), nullable=True),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_game_id', name='uq_games_platform_game_id')
    )
    op.create_index(op.f('ix_games_user_id'), 'games', ['user_id'], unique=False)
    op.create_table('game_positions',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('game_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('ply', sa.BIGINT(), nullable=False),
    sa.Column('full_hash', sa.BIGINT(), nullable=False),
    sa.Column('white_hash', sa.BIGINT(), nullable=False),
    sa.Column('black_hash', sa.BIGINT(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_positions_game_id'), 'game_positions', ['game_id'], unique=False)
    op.create_index('ix_gp_user_black_hash', 'game_positions', ['user_id', 'black_hash'], unique=False)
    op.create_index('ix_gp_user_full_hash', 'game_positions', ['user_id', 'full_hash'], unique=False)
    op.create_index('ix_gp_user_white_hash', 'game_positions', ['user_id', 'white_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gp_user_white_hash', table_name='game_positions')
    op.drop_index('ix_gp_user_full_hash', table_name='game_positions')
    op.drop_index('ix_gp_user_black_hash', table_name='game_positions')
    op.drop_index(op.f('ix_game_positions_game_id'), table_name='game_positions')
    op.drop_table('game_positions')
    op.drop_index(op.f('ix_games_user_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
