"""Assemble the tilt technical report (stories/tilt/tilt-report.md) from the story tables.

Prose lives here; every table is rendered from analysis/out/tilt/story/*.csv, which
gen_story.py writes, so the report can never drift from the numbers.

Run: uv run --project analysis python analysis/tilt_study/gen_story.py
     uv run --project analysis python analysis/tilt_study/gen_report.py
"""

import json
from pathlib import Path

import polars as pl

REPO = Path(__file__).resolve().parents[2]
STORY = REPO / "analysis" / "out" / "tilt" / "story"
REPORT = REPO / "stories" / "tilt" / "tilt-report.md"
DATE = "2026-09-08"


def load(name: str) -> pl.DataFrame:
    return pl.read_csv(STORY / f"{name}.csv")


def fmt_cell(v: object) -> str:
    if v is None:
        return ""
    if isinstance(v, float):
        return f"{v:.1f}" if abs(v) < 1000 else f"{v:,.0f}"
    if isinstance(v, int):
        return f"{v:,}"
    return str(v)


def table(df: pl.DataFrame, cols: list[tuple[str, str]] | None = None) -> str:
    """Markdown table; cols = [(source column, header)] to select and rename."""
    if cols:
        df = df.select([pl.col(c).alias(h) for c, h in cols])
    head = "| " + " | ".join(df.columns) + " |\n|" + "---|" * len(df.columns)
    body = "\n".join("| " + " | ".join(fmt_cell(v) for v in row) + " |" for row in df.iter_rows())
    return head + "\n" + body


def ci(df: pl.DataFrame, mean: str, lo: str, hi: str, name: str) -> pl.DataFrame:
    return df.with_columns(
        (
            pl.col(mean).map_elements(lambda v: f"{v:+.1f}", return_dtype=pl.Utf8)
            + " ["
            + pl.col(lo).map_elements(lambda v: f"{v:+.1f}", return_dtype=pl.Utf8)
            + ", "
            + pl.col(hi).map_elements(lambda v: f"{v:+.1f}", return_dtype=pl.Utf8)
            + "]"
        ).alias(name)
    )


def xlab(x: int) -> str:
    k = abs(x)
    if x == 0:
        return "draw"
    return f"{k}{'+' if k == 6 else ''} {'loss' if x < 0 else 'win'}{'es' if (k > 1 and x < 0) else ('s' if k > 1 else '')}"


pop = json.loads((STORY / "population.json").read_text())
trait = json.loads((STORY / "trait.json").read_text())

lad = (
    load("ladder6")
    .filter(pl.col("x") != 0)
    .with_columns(pl.col("x").map_elements(xlab, return_dtype=pl.Utf8).alias("streak"))
)
lad = ci(lad, "resid", "resid_lo", "resid_hi", "tilt")
curve_tc = load("streak_curve_tc").filter(pl.col("x") != 0)
curve_elo = load("streak_curve_elo").filter(pl.col("x") != 0)
colour = load("streak_curve_colour_check").filter(pl.col("x") != 0)
form = load("form_control")
fe = load("streak_curve_player_fe").filter(pl.col("x") != 0)
s3tc = ci(
    ci(load("streak3_by_tc"), "cold_resid", "cold_lo", "cold_hi", "after 3+ losses"),
    "hot_resid",
    "hot_lo",
    "hot_hi",
    "after 3+ wins",
)
s3elo = ci(
    ci(load("streak3_by_rating"), "cold_resid", "cold_lo", "cold_hi", "after 3+ losses"),
    "hot_resid",
    "hot_lo",
    "hot_hi",
    "after 3+ wins",
)
s3cell = ci(
    ci(load("streak3_by_cell"), "cold_resid", "cold_lo", "cold_hi", "after 3+ losses"),
    "hot_resid",
    "hot_lo",
    "hot_hi",
    "after 3+ wins",
)
brk = ci(
    ci(load("break_test"), "cold_resid", "cold_lo", "cold_hi", "after 2+ losses"),
    "hot_resid",
    "hot_lo",
    "hot_hi",
    "after 2+ wins",
)
brk = ci(brk, "gap_hot_minus_cold", "gap_lo", "gap_hi", "gap (hot minus cold)")
stop = load("stop_rule")
fatigue = load("fatigue")
ploss = load("p_loss_after_k")
quit_ = load("quit_rush")
rev = load("revenge")
rev_elo = load("revenge_by_rating")
speed = load("speed")
blunders = load("blunders")
shape = load("next_loss_shape")
analysed = ci(
    ci(
        load("analysed_by_streak").with_columns(
            pl.col("x").map_elements(xlab, return_dtype=pl.Utf8).alias("streak")
        ),
        "analysed_pct",
        "analysed_lo",
        "analysed_hi",
        "analysed % [95% CI]",
    ),
    "demeaned_pp",
    "demeaned_lo",
    "demeaned_hi",
    "vs player's own rate, pp [95% CI]",
).with_columns(pl.col("analysed % [95% CI]").str.replace_all(r"\+", ""))  # rates are unsigned
analysed = ci(analysed, "deep_pp", "deep_lo", "deep_hi", "same, session games 6–15 only [95% CI]")


def anat(name: str) -> str:
    d = load(name)
    cols = [("previous loss", "previous loss")]
    for tc in ["all", "bullet", "blitz", "rapid", "classical"]:
        d = ci(d, f"{tc}_resid", f"{tc}_lo", f"{tc}_hi", tc)
        cols.append((tc, tc))
    cols.insert(1, ("all_n", "games"))
    return table(d, cols)


def pivot_curve(df: pl.DataFrame, key: str, col: str) -> str:
    p = df.pivot(on="x", index=key, values=col)
    p = p.rename({c: xlab(int(c)) for c in p.columns if c != key})
    return table(p)


md = f"""# Tilt: the game after a losing streak. Technical report

Companion to the data story [You've lost three in a row. Should you stop?](https://stories.flawchess.com/tilt/)
(published {DATE}). Every number in the story comes from the tables below, which are generated by
`analysis/tilt_study/gen_story.py` from the cached extracts of the FlawChess benchmark database; this
document is assembled by `analysis/tilt_study/gen_report.py`. The exploratory analysis that preceded the
story, including a review of the published literature, is in `analysis/tilt_study/FINDINGS.md`.

## TL;DR

1. **In raw game history the streak effect looks enormous**: the game after 6+ straight losses scores
   43.4%, after 6+ straight wins 65.4% (a 22-point swing). Almost all of it is opponent selection (long
   streaks happen against weaker opponents: rematch series, arenas, the thin top of the pool), streaks that
   span more than one sitting, and account artefacts (rating drift, second accounts). Holding those fixed
   leaves 47.2% vs 54.1%, and against the rating-based expectation (49.8% / 51.5%) the residual is
   **−2.6 / +2.6 points** (§1).
2. **Tilt is real, small and grows with the streak.** Residual after 1, 2, 3, 4, 5, 6+ losses: −0.3, −1.0,
   −0.8, −0.7, −1.8, −2.6 points of score; after wins +0.3, +0.6, +1.2, +1.1, +1.8, +2.6. The probability of
   losing the next game crosses 50% only after six straight losses (§2).
3. **Slow games tilt harder; beginners tilt most.** After 3+ losses: bullet −0.9, blitz −0.8, rapid −1.9;
   800-rated players −2.2, everyone from 1200 up −0.6 to −0.9. The hot hand is +1.3 to +1.7 everywhere (§3).
4. **A break does not reset the state; time does.** The hot-minus-cold gap after a 2+ streak is ≈2 points
   for any break under 30 minutes and ≈0 beyond, though the two sides fade differently: the hot hand is
   gone after a few minutes, the cold effect deepens for half an hour. A "stop after two losses" rule
   would have saved 0.10 points per 100 games (§4).
5. **Blown endgames do not tilt you; quick collapses and disconnects do.** Next-game residual after a loss
   that entered the endgame at ≥ +2: +0.2 (two thirds are flags; blown by resignation −0.3 with a wide
   interval); after a loss in ≤ 20 plies: −2.1; after an abandoned game: −3.5. Games thrown away before
   the endgame are not separable from other short losses in this cut (§5).
6. **Tilt is behavioural first.** After a loss players move 2–4% faster, quit sessions more often (bullet:
   21.7% vs 16.2%), rush the next game (rapid: 53% vs 43% within a minute), and lose the revenge rematch
   (−1.7 vs −0.5 against a new opponent, about a point of which is mood rather than matchup). Blunder
   rates are unchanged after one loss and up ≈0.5 per 100 moves after three (§6).
7. **Tilt-proneness is a weak trait**: split-half r = {trait["split_half_r"]:.2f}, so an individual's
   own tilt number from ~300 games is mostly noise (§7).

## Data and method

- **Population**: {pop["games_total"]:,} rated games against humans with both ratings known, played by
  {pop["users"]:,} Lichess users in the FlawChess benchmark database (≈200 users per rating × time-control
  cell, ≈300 games each, {pop["first_game_at"][:10]} to {pop["last_game_at"][:10]}). Games with a clock
  record: {pop["share_with_clock_duration"]:.1f}%.
- **Unit**: consecutive games of one user in one time-control bucket (bullet / blitz / rapid / classical),
  ordered by start time. A user's games in other buckets are a separate stream.
- **Game end** = start + time used by both sides from the `%clk` annotations (`2·base + inc·plies − last
  clocks`); fallback median seconds per ply of the bucket. Breaks and sessions are measured from the end
  of the previous game. A gap of ≥ 60 minutes starts a new session.
- **Streak**: run of same-result games ending at the previous game. Draws break streaks and are shown
  as their own cell where relevant.
- **Equal footing** (stories/CLAUDE.md rule): only games in which the two players are within 100 rating
  points are *scored* ({pop["games_scored_equal_footing"]:,} games, 77.8%). Sequence features (streaks,
  breaks, sessions, rematches) use the full history.
- **Expected score**: empirical mean score in the same (time control, 400-point rating bucket at game
  time, 25-point rating-gap bin, colour), fitted on the frame the story scores: equal-footing, hygiene-clean
  games that are not the first game of a session (so the residual averages zero on that frame, by time
  control and by rating). Fitting on all equal-footing games instead put the zero point on a population
  that includes the cold-start first games of a session, which shifted every in-session cell by a
  time-control-specific offset (bullet +0.4, rapid −0.3, classical −1.7 pp) and made the bullet-vs-rapid
  contrast in §3 largely a warm-up artefact. Lichess ratings are not quite Elo-calibrated (a 100–149-point
  favourite scores 63%, not the 67% the Elo formula gives; the logistic scale is ≈520 in blitz, not 400),
  so the Elo formula would fake a hot hand for favourites. **Residual = score − expected**, reported in
  percentage points (pp) of score; 1 pp is one extra loss (a win turned into a loss) per 100 games.
- **Story hygiene** (applied to every scored number in the story unless stated): drop each user's first
  100 imported games in the time control and games played more than 150 points from the user's long-run
  median rating in that time control (second accounts, resets, rating drift). The import is the most recent
  1,000 games in a 36-month window, so the first 100 are mostly the oldest games of an established account
  rather than provisional ones; what they carry is rating drift (mean |rating − median| 62 vs 36 later,
  residual +0.5 pp), plus the odd new account. The rating-deviation filter conditions on the outcome (a long
  streak moves the rating) but drops only 2–4% of games;
  {pop["games_scored_story_hygiene"]:,} games remain. Streak statistics also require the streak to lie
  within one session and the next game to start within the hour: {pop["games_after_same_session_streak"]:,}
  games (bullet {pop["after_streak_bullet"]:,}, blitz {pop["after_streak_blitz"]:,}, rapid
  {pop["after_streak_rapid"]:,}, classical {pop["after_streak_classical"]:,}).
- **Intervals**: 95% bootstrap over users (a user's games are correlated), 1,000 resamples for the
  headline curve, 300 elsewhere. Differences between groups (break test gap) resample users jointly.
- **Streak-selection bias** (Miller–Sanjurjo) does not apply: statistics are pooled over games, not
  averaged per session.

## 1. The control ladder

Next-game score (%) by the streak that just ended. Columns left to right add one control each:
any opponent and any gap (raw history) → equal-footing next game → streak within one session and next
game within the hour → account hygiene. "Expected" is the calibrated expectation for the controlled
games; "tilt" is the residual with its 95% interval.

{table(lad, [("streak", "streak"), ("n_any", "games (raw)"), ("any_opponent", "raw history"), ("equal_footing", "+ equal footing"), ("same_session", "+ one session"), ("controlled", "+ hygiene (controlled)"), ("n_controlled", "games (controlled)"), ("expected", "expected"), ("tilt", "tilt [95% CI]")])}

Why the raw curve is steep (all games, by streak; the 6+ cells are pooled from the 7+ axis in
`ladder_diagnostics.csv`): after 6+ wins the next opponent is on average 175 points weaker, after 6+
losses 61 points stronger (the rating sits only 8–10 points above its long-run median at that point, so
this is selection, not rating lag: streaks happen against weak opposition, in rematch series, in arenas
and at the thin top of the pool); only 27–30% of 6+ streaks lie within one session (41% span more than a
day); 17–19% of the games after a 6+ streak fall in the user's first 100 games (baseline 15%); 3.5–4.2%
are played more than 150 points off the user's median rating (baseline 2%).

{table(load("ladder_diagnostics"), [("x", "streak (−7 = 7+ losses)"), ("n", "games"), ("mean_rating_gap_next_game", "mean rating gap, next game"), ("share_equal_footing", "share equal footing"), ("share_streak_in_one_session", "share streak in one session"), ("share_in_first_100_games", "share in first 100 games"), ("rating_minus_long_run_median", "rating − long-run median")])}

## 2. The controlled streak curve

Same games as the last column of §1. Raw next-game score, expectation and residual by exact streak
length, ±6 pooled (6 or more).

{table(load("streak_curve").filter(pl.col("x") != 0).with_columns(pl.col("x").map_elements(xlab, return_dtype=pl.Utf8).alias("streak")).pipe(ci, "resid", "resid_lo", "resid_hi", "tilt"), [("streak", "streak"), ("n", "games"), ("score", "next-game score"), ("score_lo", "score lo"), ("score_hi", "score hi"), ("expected", "expected"), ("tilt", "tilt [95% CI]")])}

Raw probability of losing the next game after k straight losses (same games):

{table(ploss, [("k", "k losses in a row"), ("n", "games"), ("p_loss_pct", "P(lose next) %"), ("p_win_pct", "P(win next) %"), ("score_pct", "score %"), ("expected_pct", "expected %")])}

### 2a. By time control (residual, pp)

{pivot_curve(curve_tc, "tc", "resid")}

Cell sizes (games):

{pivot_curve(curve_tc, "tc", "n")}

Classical has 10–60 games per tail cell after the same-session requirement (its regular players play
one or two games per sitting) and is reported here only; the story charts bullet, blitz and rapid.

### 2b. By rating (residual, pp)

{pivot_curve(curve_elo, "elo_bucket", "resid")}

{pivot_curve(curve_elo, "elo_bucket", "n")}

### 2c. Robustness checks

**Colour.** The expectation is fitted per colour. Refitting it without colour changes no cell by more
than 0.1 pp:

{table(colour, [("x", "streak"), ("resid", "residual (colour-aware)"), ("resid_nocolour", "residual (colour-blind)")])}

**Trailing form.** Form = mean residual over the 20 scored games ending four games before the current
one (never overlapping the 3-game streak window), split into terciles. The streak effect has the same
size inside every tercile, so it is not a 20-game form window in disguise:

{table(form, [("form_tercile", "form tercile"), ("mean_form_pp", "mean form (pp)"), ("LLL+", "after LLL+"), ("L", "after L"), ("W", "after W"), ("WWW+", "after WWW+")])}

**Player fixed effects.** Subtracting each user × time-control mean residual (over all their scored
games) from the residual removes the part of the tail that comes from players who generally beat or
trail their rating. The cold tail survives; the hot tail shrinks by about a third:

{table(fe, [("x", "streak"), ("n", "games"), ("resid", "residual"), ("resid_player_fe", "residual, player-demeaned"), ("lo", "lo"), ("hi", "hi"), ("mean_player_fe", "mean player effect")])}

## 3. Who tilts: rating and time control

Residual after 3+ straight losses (cold) and 3+ straight wins (hot), same-session streaks, hygiene.

{table(s3tc, [("tc", "time control"), ("cold_n", "games after 3+ L"), ("cold_score", "score after L"), ("cold_expected", "expected after L"), ("after 3+ losses", "tilt [95% CI]"), ("hot_n", "games after 3+ W"), ("hot_score", "score after W"), ("hot_expected", "expected after W"), ("after 3+ wins", "hot hand [95% CI]")])}

{table(s3elo, [("elo_bucket", "rating"), ("cold_n", "games after 3+ L"), ("cold_score", "score after L"), ("cold_expected", "expected after L"), ("after 3+ losses", "tilt [95% CI]"), ("hot_n", "games after 3+ W"), ("hot_score", "score after W"), ("hot_expected", "expected after W"), ("after 3+ wins", "hot hand [95% CI]")])}

Rating × time control (cells under 1,000 games are noise-level; classical 2400 has no same-session
3+ streaks after the equal-footing filter):

{table(s3cell, [("cellk", "cell"), ("cold_n", "games after 3+ L"), ("after 3+ losses", "tilt [95% CI]"), ("hot_n", "games after 3+ W"), ("after 3+ wins", "hot hand [95% CI]")])}

## 4. Breaks, the stop rule, warm-up and fatigue

Streak of 2+ within one session; next game bucketed by the break between the end of the last streak
game and its start. Residual after 2+ losses (cold) and 2+ wins (hot), and the hot-minus-cold gap with a
joint user bootstrap. Levels are self-selected (who pauses after two losses is not random); the gap
between the two groups at the same break length is the robust quantity.

{table(brk, [("tc", "time control"), ("break", "break"), ("cold_n", "games (cold)"), ("after 2+ losses", "after 2+ losses [CI]"), ("hot_n", "games (hot)"), ("after 2+ wins", "after 2+ wins [CI]"), ("gap (hot minus cold)", "gap [CI]")])}

Who takes which break (share of next games, %; `break_shares.csv`): after 2+ losses, 72% of bullet and
60% of rapid next games start within a minute; after 2+ wins 75% and 46%. Rapid players are the ones
who *rush* after losses.

**Stop-after-two-losses counterfactual.** Share of scored games that follow 2+ same-session losses,
their residual, and the product (points of score per 100 games the rule would have saved; equal to
extra losses per 100 games):

{table(stop.with_columns((-pl.col("score_pts_saved_per_100_games")).map_elements(lambda v: f"{v:.2f}", return_dtype=pl.Utf8).alias("saved")), [("tc", "time control"), ("games_after_LL_in_session", "games after LL"), ("share_of_games", "share of games %"), ("resid_pp", "residual"), ("lo", "lo"), ("hi", "hi"), ("saved", "points saved / 100 games")])}

This is the saving for players who continued within the hour; players who did stop are unobserved.

**Warm-up and fatigue.** Residual for the first game of a session and by minutes since the session
started (games after the first):

{table(fatigue, [("tc", "time control"), ("first_game_n", "first games"), ("first_game_resid", "first game of session"), ("first_lo", "lo"), ("first_hi", "hi"), ("0-30 min", "0–30 min"), ("30-60 min", "30–60 min"), ("60-120 min", "60–120 min"), ("2-4 h", "2–4 h"), (">4 h", "> 4 h")])}

Bullet needs a warm-up game (−2.2) and shows no fatigue over 4+ hours; rapid and classical drift down by
about 1 pp after one to four hours. (Residuals here are relative to in-session games, which is why the
first-game cells are negative and the in-session cells sit near zero.)

## 5. Which loss tilts you

Next-game residual after a loss (previous game lost, next game within the hour, equal footing, hygiene),
by how the loss ended, how long it lasted, and the Stockfish evaluation when it entered the endgame
(Lichess phase rule; ≥ +2.0 for the player = "blown"; no endgame = the game ended in the opening or
middlegame). "all" pools the four time controls.

By termination:

{anat("loss_by_termination")}

By length:

{anat("loss_by_length")}

By endgame state:

{anat("loss_by_endgame")}

Blown wins by how the blown game ended. Two thirds are flags in a won endgame; the blown win by
resignation, the folklore case, is 11k games with an interval that excludes anything large but not a
small effect. A game thrown away before the endgame (a hung piece in the middlegame) has no endgame entry
and lands in the "never reached an endgame" cell, so this cut cannot separate it from other short losses:

{anat("loss_blown_by_termination")}

Endgame state inside long losses only (> 60 plies), so the endgame cut is not length in disguise:

{anat("loss_by_endgame_long")}

Single losses only (streak length exactly 1), to show the cut is not streak length in disguise:

{anat("loss_by_length_single")}

{anat("loss_by_endgame_single")}

Mirror: the game after a **win**, by endgame state and length:

{anat("win_by_endgame")}

{anat("win_by_length")}

Shape of the next loss after a streak (conditional on losing the next game): after a losing streak the
loss is shorter, more often abandoned and more often resigned:

{table(shape, [("tc", "time control"), ("grp", "after"), ("n", "losses"), ("short_loss_pct", "≤ 20 plies %"), ("abandoned_pct", "abandoned %"), ("resigned_pct", "resigned %"), ("flagged_pct", "flagged %"), ("mean_plies", "mean plies")])}

## 6. Behaviour: quitting, rushing, revenge, speed, blunders

**Quit and rush** (all rated games with hygiene; a session ends when the next game starts ≥ 60 min
after this one ends):

{table(quit_, [("tc", "time control"), ("quit_after_loss", "P(session ends) after a loss %"), ("quit_after_win", "P(session ends) after a win %"), ("next_within_60s_after_loss", "next game < 60 s after a loss %"), ("next_within_60s_after_win", "next game < 60 s after a win %"), ("median_gap_after_loss_s", "median gap after a loss (s)"), ("median_gap_after_win_s", "after a win (s)"), ("sessions_ending_on_loss_pct", "sessions ending on a loss %"), ("base_loss_rate_pct", "base loss rate %")])}

**Revenge rematch**: next game, within the hour, against the same opponent. Residual for the rematch
vs a fresh opponent, after a loss and after a win (equal footing, hygiene). The rematch-minus-fresh
difference is the cost of the decision (−1.2 pooled, −1.4 for the first rematch of a pairing). Opponent
selection (the player who just beat you is, on that evidence, a little better than their rating) predicts
a symmetric bonus after wins, and the first post-win rematch shows one (+0.5 over a fresh opponent),
so roughly a third of the post-loss penalty is matchup and the rest (≈ −1 pp) is state:

{table(rev, [("tc", "time control"), ("rematch_rate_after_loss", "rematch rate after L %"), ("rematch_n_after_loss", "rematches"), ("rematch_score_after_loss", "score"), ("rematch_expected_after_loss", "expected"), ("rematch_resid_after_loss", "rematch residual"), ("rematch_lo_after_loss", "lo"), ("rematch_hi_after_loss", "hi"), ("fresh_resid_after_loss", "fresh-opponent residual"), ("rematch_rate_after_win", "rematch rate after W %"), ("rematch_resid_after_win", "rematch residual after W"), ("fresh_resid_after_win", "fresh residual after W")])}

{table(rev_elo, [("elo_bucket", "rating"), ("rematch_rate_after_loss", "rematch rate after L %"), ("rematch_n_after_loss", "rematches"), ("rematch_resid_after_loss", "revenge residual"), ("lo_after_loss", "lo"), ("hi_after_loss", "hi"), ("rematch_rate_after_win", "rematch rate after W %"), ("rematch_resid_after_win", "rematch residual after W")])}

First rematch of a pairing vs later games in a series against the same opponent, with the rematch-minus-fresh
difference and its joint user bootstrap:

{table(ci(load("revenge_series"), "rematch_minus_fresh", "diff_lo", "diff_hi", "rematch − fresh [95% CI]"), [("after", "after"), ("position", "position"), ("n", "rematches"), ("rematch_resid", "rematch residual"), ("lo", "lo"), ("hi", "hi"), ("fresh_resid", "fresh residual"), ("rematch − fresh [95% CI]", "rematch − fresh [95% CI]")])}

**Speed**: mean seconds per move over moves 3–20 (own moves with a clock delta, ≥ 10 such moves) and the
share of those moves played in ≤ 1 s, by the streak just ended; plus the paired per-user relative change
in seconds per move after a loss vs after a win (users with ≥ 20 games in each cell):

{table(speed, [("tc", "time control"), ("think_s_LLL+", "s/move after LLL+"), ("think_s_L", "after L"), ("think_s_W", "after W"), ("think_s_WWW+", "after WWW+"), ("fast_moves_pct_L", "≤ 1 s moves after L %"), ("fast_moves_pct_W", "≤ 1 s moves after W %"), ("paired_users", "paired users"), ("paired_rel_change_pct", "paired change after L vs W %"), ("share_users_faster_after_loss", "share of users faster after L %")])}

**Move quality**: blunders per 100 own moves in the uniformly analysed arm (games with full FlawChess
Stockfish evaluation, rapid and classical, ≥ 20 plies), own and opponent's, by streak. After a single
loss the rate is unchanged (6.4 vs 6.4 after a win, where the score effect is also ≈ 0). After 3+ losses
it rises by ≈ 0.5 per 100 moves (rapid 7.0 [6.7, 7.3] vs 6.4 [6.2, 6.6]), in line with the score effect.
The opponent's rate rises in the same games, which is consistent with a game-mix effect but also with a
tilted player steering into sharper, faster games; the data cannot separate the two. Note that this arm
is the complement of the user-requested-analysis set and inherits that selection:

{table(blunders, [("tc", "time control"), ("blunders_per_100_LLL+", "own, after LLL+"), ("opp_blunders_LLL+", "opponent, after LLL+"), ("blunders_per_100_L", "own, after L"), ("opp_blunders_L", "opponent, after L"), ("blunders_per_100_W", "own, after W"), ("opp_blunders_W", "opponent, after W"), ("blunders_per_100_WWW+", "own, after WWW+"), ("opp_blunders_WWW+", "opponent, after WWW+"), ("n_L", "games after L")])}

The lichess-analysed (user-requested) evaluations are not used for this: analysis requests are
themselves tilt-dependent (§6a), which produces a spurious +15–20% ACPL after LLL+ (FINDINGS.md,
additional probes).

### 6a. Analysis requests: does a tilted player still look at the game?

Share of games with a Lichess computer analysis (`lichess_evals_at` set; either player can request
it), by the streak the game *completes*: the row "3 losses" is the third straight loss itself, not the
game after it. All rated games with hygiene, the run within one session, ±6 pooled, intervals from the
user bootstrap. Two controls: "vs player's own rate" subtracts each user × time-control mean analysis
rate from the game's flag, which removes who reaches long streaks; "session games 6–15 only" additionally
compares streak lengths at the same session depth, because a k-game streak sits at least k games into
its session and the per-game analysis rate falls with session length whatever the result (rapid: 40%
in one-game sessions, 25% at 8+), and because the game a player stops on is analysed more often (rapid
losses: 37% vs 32%) while a streak game is by construction less often the stopping game (37% → 18%
from 1 to 6+ losses). The last two columns are the rapid raw rate and the rapid depth-controlled rate:

{table(analysed, [("streak", "streak completed"), ("n", "games"), ("analysed % [95% CI]", "analysed % [95% CI]"), ("vs player's own rate, pp [95% CI]", "vs player's own rate, pp [95% CI]"), ("same, session games 6–15 only [95% CI]", "same, session games 6–15 only [95% CI]"), ("bullet_analysed_pct", "bullet %"), ("blitz_analysed_pct", "blitz %"), ("rapid_analysed_pct", "rapid %"), ("rapid_deep_pp", "rapid, controlled pp")])}

The raw column falls from 22.7% after a single loss to 14.7% after 6+ straight losses (rapid: 34.1% →
21.4%), but most of that is not a decision to look away. Three mechanical things drive it: who reaches
long same-session streaks (bullet players at 8% whatever the streak, high-volume accounts, and in rapid
a rating that drifts from 1,700 in the 1-loss cell to 1,480 at 6+; lower-rated players analyse less),
session depth, and the stop-and-analyse selection above. Game shape is not one of them: length (62–68
plies) and abandonment rate (2.6%) are flat across the loss cells, and dropping rematches changes
nothing. Demeaning by user removes about two thirds of the drop; holding session depth fixed removes
most of the rest. What survives is small and consistent in sign: at equal depth, within a player, a
single loss is analysed 1.4 pp more often than that player's average game, 6+ losses 0.2 pp (rapid:
+3.0 → +0.4), while wins sit 1.2–2.1 pp below the player's mean at every streak length (rapid: −4.8 →
−5.8). The loss-specific part of the decline is ≈ 1 pp pooled and ≈ 2 pp in rapid, on bases of 20%
and 28%; the trend is monotonic from 1 to 5 losses, but the 6+ cell alone has an interval of ± 1 pp
pooled and ± 3 pp in rapid, so this is suggestive rather than established. The rising raw rate after
long winning streaks is the mirror artefact (rapid 6+-win streaks come from 1,980-rated players who
analyse more; within player the win rate is flat). Draws are the most analysed result in raw terms
(28.2%) but −1.5 pp within player: draw-heavy players are the rapid and classical crowd. The
population-level fact the blunder analysis in §6 relies on (analysis requests are tilt-dependent)
stands, mostly through composition and session depth rather than mood.

## 7. Is tilt a personal trait?

Per user × time control: Δ = mean residual after a loss − mean residual after a win, computed
separately on odd- and even-numbered sessions (≥ 25 scored games per side per half). The SD and the
correlation are taken over the same streams (both halves qualifying).

| statistic | value |
|---|---|
| user × time-control streams | {trait["streams_user_x_tc"]:,} (users: {trait["users"]:,}) |
| mean Δ (pp) | {trait["mean_delta_pp"]:+.2f} |
| observed SD of Δ across users (pp) | {trait["sd_delta_pp"]:.1f} |
| split-half correlation r | {trait["split_half_r"]:.3f} |
| Spearman–Brown reliability of a full ~300-game Δ | {trait["spearman_brown_reliability"]:.2f} |
| implied true SD of the trait (pp) | {trait["implied_true_sd_pp"]:.1f} |

Tilt-proneness is a real but weak trait: a player one SD above the mean loses ≈ 3.3 pp more after losses
than after wins. A single player's own Δ from ~300 games is ≈ 80% noise, so a per-user "tilt score" would
mislead most users; the story reports population averages.

## 8. Relation to published work

Summarised from the literature review in `analysis/tilt_study/FINDINGS.md` §8.

- **Gee, Seese, Curley & Ward (2025)**, arXiv:2503.21713, hierarchical Bayesian logit on Lichess bullet
  games of 141 players from 1700 up, controlling for rating difference, colour and player: the global
  winner/loser effect is centred on zero, individual effects within ±3 pp. Our single-game effect
  (−0.3 / +0.3) is below their detection floor; our 3+ and 6+ effects sit inside their credible range.
- **Rosenthal (2025)**, Harvard Data Science Review 7(2), 293k chess.com games of seven top players:
  autocorrelation of excess score ≈ 0 at every lag, raw-score autocorrelation ≈ 0.1 attributed to rating
  updates. Our 2000–2400 cells (tilt ≈ −0.7, CI including zero) agree, and his raw-vs-excess gap is our §1
  ladder.
- **Chowdhary, Iacopini & Battiston (2023)**, Sci. Rep. 13:2113, 123M Lichess blitz games: real streaks
  are longer than shuffled ones, cold streaks longer than hot, beginners streakier than experts. Same
  direction as ours; a shuffle test cannot separate state from rating drift, which is why their effect
  looks larger.
- **Popular analyses** (e.g. chessanalysis.co, 39% after five losses vs 58% after five wins at
  1200–1400) do not control for opponent rating, session or account state; §1 reproduces a swing of that
  size on our raw data and shows where it goes.
- Break length, loss anatomy, revenge rematches and quit-on-loss have no quantitative chess precedent
  that we found. The closest analogue is Jack J (2020) on League of Legends, where re-queuing immediately
  after two losses is worst for mid-rank players and best for top-rank players: the same inversion as our
  rapid (pause helps a little) vs bullet (play on) pattern.

## 9. Limits

- Observational throughout. Who continues, pauses, rematches or requests analysis is self-selected;
  the story leans on differences between groups facing the same selection (hot vs cold at the same break
  length; rematch vs fresh opponent after the same result) rather than on single cells. Every streak cell
  describes players who kept playing within the hour; the players who stopped are not observed, so "should
  you stop" is answered for continuers only.
- The expectation is calibrated on the pooled population; user-level rating lag remains, and it can cut
  either way (a constant-strength player is under-rated after losses, which hides tilt; an improving player
  is under-rated after wins, which inflates the hot hand). The trailing-form and player-fixed-effect checks
  (§2c) bound it: the cold tail survives both, the hot tail shrinks by about a third.
- The 30-minute fade in §4 rests on the 30–60 min cells (gap +0.1, CI −1.3 to +1.5); the true transition
  could sit anywhere between ten minutes and a few hours.
- Time of day is UTC only (no user time zone) and not analysed.
- The benchmark cohort is regular players (~300 games per time control over three years), not a uniform
  sample of Lichess. Classical is thin once streaks must lie within one session.
- The equal-footing filter removes 22% of games, disproportionately at 2400 and in classical.
- Berserk in arena games, sub-time-control mix (1+0 vs 2+1) and casual games after a loss were not
  modelled. 944 of the 4,487 users have games in a second time control; play in the other control inside
  a break gap is under 0.5% of break-test cells, so switching controls does not contaminate §4, but casual
  games in a gap are invisible.

## Reproduction

```bash
bin/benchmark_db.sh start
uv run --project analysis python analysis/tilt_study/extract_clocks.py           # clock_ends.parquet
uv run --project analysis python analysis/tilt_study/probes/extract_acc.py       # acc.parquet (colour)
uv run --project analysis python analysis/tilt_study/probes/extract_moves.py     # move_feats.parquet
uv run --project analysis python analysis/tilt_study/probes/extract_flaws.py     # flaws_byus.parquet
uv run --project analysis python analysis/tilt_study/extract_endgame_entry.py    # endgame_entry.parquet
uv run --project analysis python analysis/tilt_study/gen_story.py                # analysis/out/tilt/story/*.csv
uv run --project analysis python analysis/tilt_study/gen_report.py               # this file
```

`games.parquet` is written by the first run of the marimo notebook `analysis/tilt_study/tilt_study.py`.
"""

REPORT.write_text(md)
print(f"wrote {REPORT} ({len(md):,} chars)")
