"""Stratified puzzle selector for the tagger validation harness (Phase 127, D-07).

Reads the full lichess CC0 puzzle download (.csv.zst) and emits two committed
stratified fixtures — a TRAIN set and a held-out TEST set — to
fixtures/tagger/detector_fixture_train.csv and fixtures/tagger/detector_fixture_test.csv.

The fixture is stratified by (our_motif, Rating band) so the harness covers
each motif evenly across skill levels and can report depth-vs-Rating correlation
(D-06). Only the sampled fixtures (~thousands of rows) are committed to git; the
full puzzle download (~300 MB .zst) is NOT committed.

Train/test split (anti-overfitting):
  Each selected puzzle is assigned to TRAIN or TEST deterministically by a hash of
  its PuzzleId, so a given puzzle always lands in the same split regardless of
  sample size or seed. The self-improvement loop optimizes on TRAIN only; TEST is
  scored for honest held-out validation and never used to tune detectors or set
  floors. Because the assignment is per-puzzle (not per-stratum), the split is
  ~test_fraction within every (motif, rating-band) stratum on average.

CC0 / AGPL boundary (SC#4, D-11):
  The lichess puzzle database (database.lichess.org/#puzzles) is CC0 / Public
  Domain. The puzzle labels were generated by tagger/cook.py in the
  lichess-puzzler repository, which is AGPL-3.0. We use only the published CC0
  dataset; cook.py is neither vendored nor ported in this codebase.

FEN/Moves convention (critical — RESEARCH Pitfall 1):
  The published FEN is the position BEFORE the opponent's blunder.
  Moves[0]  = the opponent's blunder (the move that creates the puzzle position).
  Moves[1:] = the solution / refutation PV (what the player must play).
  The detector expects board-after-flaw FEN. So:
    board_after_flaw = apply Moves[0] to the published FEN
    pv_str = " ".join(Moves[1:])

Usage:
  uv run python scripts/select_tagger_fixtures.py \\
      --puzzle-path /path/to/lichess_db_puzzle_2026-06.csv.zst

  On first run the script prints the 50 most common observed theme strings so
  you can verify the hangingPiece / double-bishop-mate spellings against real
  data (RESEARCH Open Questions 1-2).
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import io
import random
import sys
from collections import Counter, defaultdict
from pathlib import Path

import chess
import zstandard as zstd

# Ensure project root is on sys.path so tests.scripts.tagger imports work.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from tests.scripts.tagger.motif_theme_map import MOTIF_TO_THEMES  # noqa: E402

# ---------------------------------------------------------------------------
# Named constants (no magic numbers per CLAUDE.md)
# ---------------------------------------------------------------------------

# Default random seed for reproducible sampling.
# Used as both the --seed argparse default and the base for per-motif re-seeds
# (hash((DEFAULT_SEED, motif))) so each motif's draw is independent (Pitfall 1).
DEFAULT_SEED: int = 42

# Number of puzzles to sample per (motif, rating_band) stratum.
# Override at the CLI with --samples-per-stratum. 200 -> ~15-17k rows total before
# the train/test split (4x the original 50/stratum fixture).
SAMPLES_PER_STRATUM: int = 200

# Fraction of selected puzzles held out as the TEST set (the rest are TRAIN).
# Override at the CLI with --test-fraction. Assignment is deterministic per PuzzleId.
TEST_FRACTION: float = 0.30

# Buckets for the deterministic PuzzleId hash split (0..99 -> test if < test_pct).
_HASH_BUCKETS: int = 100

# Minimum available puzzles in a stratum before collapsing rating bands.
# If fewer than this many matching puzzles exist in a rating band, that band
# is collapsed into the adjacent band or into the catch-all (all_ratings pool).
MIN_STRATUM_SIZE: int = 10

# Rating band boundaries (exclusive upper bounds for lower bands, inclusive for top).
# Bands: <1200 | 1200-1600 | 1600-2000 | >2000
RATING_BAND_THRESHOLDS: tuple[int, ...] = (1200, 1600, 2000)

# How many top themes to print on first run (validates motif->theme map spelling).
TOP_THEMES_DISPLAY: int = 50

# Output fixture paths (relative to project root).
_FIXTURE_DIR = Path(__file__).resolve().parents[1] / "fixtures" / "tagger"
_FIXTURE_TRAIN_PATH = _FIXTURE_DIR / "detector_fixture_train.csv"
_FIXTURE_TEST_PATH = _FIXTURE_DIR / "detector_fixture_test.csv"

# Fixture CSV column header (order matters for readers).
# PreFlawFEN = the published pre-blunder FEN (cook's game.board()). FEN = board-after-flaw.
# Storing the pre-flaw FEN lets the gate rebuild the detector board exactly as production does
# (board_before + push(flaw_move)), so the flaw move sits on the board's move stack — which is
# what production passes and what cook's recapture/first-move predicates need.
_FIXTURE_HEADER: list[str] = [
    "PuzzleId",
    "FEN",
    "PreFlawFEN",
    "FirstMove",
    "PV",
    "Themes",
    "Rating",
]


# ---------------------------------------------------------------------------
# Rating band helpers
# ---------------------------------------------------------------------------


def _rating_band(rating: int) -> str:
    """Return a string label for a rating band given RATING_BAND_THRESHOLDS."""
    for threshold in RATING_BAND_THRESHOLDS:
        if rating < threshold:
            return f"lt{threshold}"
    return f"gt{RATING_BAND_THRESHOLDS[-1]}"


def _all_rating_bands() -> list[str]:
    """Return the ordered list of all rating band labels."""
    bands: list[str] = []
    for threshold in RATING_BAND_THRESHOLDS:
        bands.append(f"lt{threshold}")
    bands.append(f"gt{RATING_BAND_THRESHOLDS[-1]}")
    return bands


# ---------------------------------------------------------------------------
# Board-after-flaw helper
# ---------------------------------------------------------------------------


def _board_after_flaw(fen: str, first_move_uci: str) -> chess.Board | None:
    """Apply the opponent's blunder move to the published FEN.

    Returns the resulting board (board-after-flaw), or None if parsing fails.
    python-chess handles castling, en passant, and promotion correctly.
    """
    try:
        board = chess.Board(fen)
        move = chess.Move.from_uci(first_move_uci)
        board.push(move)
        return board
    except (ValueError, AssertionError):
        return None


# ---------------------------------------------------------------------------
# Motif matching helper
# ---------------------------------------------------------------------------


def _puzzle_motifs(themes: list[str]) -> list[str]:
    """Return our motif strings that match the puzzle's lichess theme list.

    Uses MOTIF_TO_THEMES for multi-label matching (D-10): a motif matches
    if any of its mapped lichess themes is in the puzzle's theme set.
    """
    theme_set = set(themes)
    matched: list[str] = []
    for motif, lichess_themes in MOTIF_TO_THEMES.items():
        if theme_set.intersection(lichess_themes):
            matched.append(motif)
    return matched


# ---------------------------------------------------------------------------
# Streaming reader
# ---------------------------------------------------------------------------


def _stream_puzzle_csv(puzzle_path: Path) -> list[dict[str, str]]:
    """Stream the .csv.zst puzzle file and return all matching puzzle rows.

    Returns a list of dicts with keys:
      PuzzleId, FEN (board-after-flaw), FirstMove, PV, Themes (space-joined),
      Rating (string).
    Only puzzles with at least one motif in MOTIF_TO_THEMES are returned.

    Also prints the 50 most common theme strings observed (for map validation).
    """
    dctx = zstd.ZstdDecompressor()
    theme_counter: Counter[str] = Counter()
    results: list[dict[str, str]] = []
    rows_seen = 0

    with open(puzzle_path, "rb") as fh:
        with dctx.stream_reader(fh) as reader:
            text_stream = io.TextIOWrapper(reader, encoding="utf-8", errors="replace")
            csv_reader = csv.DictReader(text_stream)
            for row in csv_reader:
                rows_seen += 1
                if rows_seen % 500_000 == 0:
                    print(f"  scanned {rows_seen:,} puzzles ...", flush=True)

                themes_raw = row.get("Themes", "").strip()
                themes: list[str] = themes_raw.split() if themes_raw else []
                for theme in themes:
                    theme_counter[theme] += 1

                matched_motifs = _puzzle_motifs(themes)
                if not matched_motifs:
                    continue

                rating_str = row.get("Rating", "0").strip()
                try:
                    rating = int(rating_str)
                except ValueError:
                    continue

                fen_raw = row.get("FEN", "").strip()
                moves_raw = row.get("Moves", "").strip()
                puzzle_id = row.get("PuzzleId", "").strip()
                if not fen_raw or not moves_raw or not puzzle_id:
                    continue

                moves_list = moves_raw.split()
                if not moves_list:
                    continue
                first_move = moves_list[0]
                pv_moves = moves_list[1:]

                board = _board_after_flaw(fen_raw, first_move)
                if board is None:
                    continue

                board_after_fen = board.fen()
                pv_str = " ".join(pv_moves)

                results.append(
                    {
                        "PuzzleId": puzzle_id,
                        "FEN": board_after_fen,
                        "PreFlawFEN": fen_raw,
                        "FirstMove": first_move,
                        "PV": pv_str,
                        "Themes": themes_raw,
                        "Rating": rating_str,
                        # internal: used for stratification, stripped before emitting
                        "_rating_int": str(rating),
                        "_matched_motifs": ",".join(matched_motifs),
                    }
                )

    print(f"\nScanned {rows_seen:,} puzzles total.", flush=True)
    print(f"Matching puzzles (at least one motif): {len(results):,}", flush=True)
    print(f"\nTop {TOP_THEMES_DISPLAY} themes observed (validate motif->theme map spelling):")
    for theme, count in theme_counter.most_common(TOP_THEMES_DISPLAY):
        print(f"  {theme}: {count:,}")

    return results


# ---------------------------------------------------------------------------
# Stratified sampling
# ---------------------------------------------------------------------------


# Modulus to fold the SHA-1 per-motif digest into a 32-bit int random.seed accepts.
_PER_MOTIF_SEED_MODULUS: int = 2**32


def _per_motif_seed(seed: int, motif: str) -> int:
    """Return a deterministic per-motif RNG seed from (base seed, motif).

    Uses SHA-1 over "seed:motif" rather than Python's builtin hash(), because
    hash() of a tuple containing a str is salted per-process (PYTHONHASHSEED),
    which would make the fixtures non-reproducible across runs AND break the
    Option-B isolation guarantee (each run would draw a different sample). This
    mirrors the deterministic SHA-1 approach already used by _is_test_puzzle.
    """
    digest = hashlib.sha1(f"{seed}:{motif}".encode("utf-8")).hexdigest()
    return int(digest, 16) % _PER_MOTIF_SEED_MODULUS


def _stratified_sample(
    candidates: list[dict[str, str]],
    samples_per_stratum: int = SAMPLES_PER_STRATUM,
    oversample_map: dict[str, int] | None = None,
    seed: int = DEFAULT_SEED,
) -> list[dict[str, str]]:
    """Stratified-sample N puzzles per (motif, rating_band) from candidates.

    Sampling strategy:
    1. Build a pool per (motif, rating_band).
    2. If a pool has < MIN_STRATUM_SIZE entries, collapse that band into the
       motif-level pool (all rating bands combined for that motif).
    3. Sample min(cap, pool_size) from each stratum, where cap is
       oversample_map.get(motif, samples_per_stratum) (D-EXP-02 Option B).
    4. Deduplicate by PuzzleId (a puzzle may match multiple motifs but is
       included at most once per stratum it was sampled into).

    Per-motif RNG re-seed (Pitfall 1 mitigation): before processing each motif
    the RNG is re-seeded with hash((seed, motif)) so each motif's draw is
    independent of every earlier motif's cap. This collapses the isolation
    blast radius to ONLY the multi-label leakage (puzzles co-occurring in both
    the target motif and an unaffected motif).

    Prints coverage counts per stratum for inspection.
    """
    oversample_map = oversample_map or {}

    # pool: (motif, band) -> list of candidate dicts
    pool: dict[tuple[str, str], list[dict[str, str]]] = defaultdict(list)

    for row in candidates:
        rating = int(row["_rating_int"])
        band = _rating_band(rating)
        for motif in row["_matched_motifs"].split(","):
            pool[(motif, band)].append(row)

    selected_ids: set[str] = set()
    selected: list[dict[str, str]] = []

    all_bands = _all_rating_bands()
    per_motif_fallback: dict[str, list[dict[str, str]]] = defaultdict(list)
    for (motif, _band), rows in pool.items():
        per_motif_fallback[motif].extend(rows)

    print(f"\nStratified coverage ({samples_per_stratum} per stratum, min {MIN_STRATUM_SIZE}):")
    for motif in sorted(MOTIF_TO_THEMES.keys()):
        # Per-motif re-seed (Pitfall 1): isolates each motif's draw so raising
        # one motif's cap does not change any other motif's selected PuzzleIds
        # (except for multi-label co-occurrences, which are the intended residue).
        # MUST be a deterministic hash (not builtin hash(), which is salted per
        # process) so the draw is reproducible and the isolation holds run-to-run.
        random.seed(_per_motif_seed(seed, motif))
        cap = oversample_map.get(motif, samples_per_stratum)
        for band in all_bands:
            band_pool = pool.get((motif, band), [])
            if len(band_pool) < MIN_STRATUM_SIZE:
                # Collapse: use all-bands fallback pool for this motif
                fallback_pool = per_motif_fallback.get(motif, [])
                if not fallback_pool:
                    print(f"  {motif} / {band}: 0 puzzles — skipped (collapsed + no fallback)")
                    continue
                n = min(cap, len(fallback_pool))
                sampled = random.sample(fallback_pool, n)
                new = [r for r in sampled if r["PuzzleId"] not in selected_ids]
                for r in new:
                    selected_ids.add(r["PuzzleId"])
                    selected.append(r)
                print(
                    f"  {motif} / {band}: {len(band_pool)} available — "
                    f"COLLAPSED to fallback ({len(fallback_pool)} available, "
                    f"sampled {len(new)} new)"
                )
            else:
                n = min(cap, len(band_pool))
                sampled = random.sample(band_pool, n)
                new = [r for r in sampled if r["PuzzleId"] not in selected_ids]
                for r in new:
                    selected_ids.add(r["PuzzleId"])
                    selected.append(r)
                print(
                    f"  {motif} / {band}: {len(band_pool)} available, "
                    f"sampled {n}, {len(new)} new unique"
                )

    print(f"\nTotal fixture rows: {len(selected)}")
    return selected


# ---------------------------------------------------------------------------
# Fixture writer
# ---------------------------------------------------------------------------


def _is_test_puzzle(puzzle_id: str, test_fraction: float) -> bool:
    """Deterministically assign a puzzle to the TEST set by hashing its PuzzleId.

    Stable across runs, sample sizes, and seeds: the same PuzzleId always lands in
    the same split, so train/test never leak into each other when re-sampling.
    """
    digest = hashlib.sha1(puzzle_id.encode("utf-8")).hexdigest()
    bucket = int(digest, 16) % _HASH_BUCKETS
    return bucket < round(test_fraction * _HASH_BUCKETS)


def _split_train_test(
    rows: list[dict[str, str]], test_fraction: float
) -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    """Partition selected rows into (train, test) by deterministic PuzzleId hash."""
    train: list[dict[str, str]] = []
    test: list[dict[str, str]] = []
    for row in rows:
        if _is_test_puzzle(row["PuzzleId"], test_fraction):
            test.append(row)
        else:
            train.append(row)
    return train, test


def _write_fixture(rows: list[dict[str, str]], output_path: Path) -> None:
    """Write the sampled rows to a fixture CSV (D-07 committed fixture)."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=_FIXTURE_HEADER, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)
    print(f"  {output_path.name}: {len(rows)} rows -> {output_path}")


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(__doc__ or "").split("\n\n")[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--puzzle-path",
        required=True,
        type=Path,
        help="Path to the lichess puzzle CSV download (.csv.zst)",
    )
    parser.add_argument(
        "--train-output",
        type=Path,
        default=_FIXTURE_TRAIN_PATH,
        help=f"Output TRAIN fixture path (default: {_FIXTURE_TRAIN_PATH})",
    )
    parser.add_argument(
        "--test-output",
        type=Path,
        default=_FIXTURE_TEST_PATH,
        help=f"Output TEST fixture path (default: {_FIXTURE_TEST_PATH})",
    )
    parser.add_argument(
        "--samples-per-stratum",
        type=int,
        default=SAMPLES_PER_STRATUM,
        help=f"Puzzles to sample per (motif, rating-band) stratum (default: {SAMPLES_PER_STRATUM})",
    )
    parser.add_argument(
        "--test-fraction",
        type=float,
        default=TEST_FRACTION,
        help=f"Fraction of selected puzzles held out as TEST (default: {TEST_FRACTION})",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=DEFAULT_SEED,
        help=f"Random seed for reproducible sampling (default: {DEFAULT_SEED})",
    )
    parser.add_argument(
        "--oversample-motifs",
        nargs="*",
        default=[],
        metavar="MOTIF:N",
        help=(
            "Per-motif oversample caps as 'motif:N' pairs (D-EXP-02 Option B). "
            "Raises the per-stratum sample cap for the named motif(s) only. "
            "Example: --oversample-motifs trapped-piece:1000 en-passant:500"
        ),
    )
    args = parser.parse_args()

    if not 0.0 < args.test_fraction < 1.0:
        print("ERROR: --test-fraction must be in (0, 1).", file=sys.stderr)
        sys.exit(1)

    # Parse --oversample-motifs tokens into a dict[str, int].
    oversample_map: dict[str, int] = {}
    for token in args.oversample_motifs or []:
        parts = token.split(":")
        if len(parts) != 2:
            print(
                f"ERROR: --oversample-motifs token {token!r} must be 'motif:N'.",
                file=sys.stderr,
            )
            sys.exit(1)
        motif_key, cap_str = parts
        if motif_key not in MOTIF_TO_THEMES:
            print(
                f"ERROR: --oversample-motifs motif {motif_key!r} is not a known "
                f"MOTIF_TO_THEMES key. Known keys: {sorted(MOTIF_TO_THEMES)}",
                file=sys.stderr,
            )
            sys.exit(1)
        try:
            cap_val = int(cap_str)
        except ValueError:
            print(
                f"ERROR: --oversample-motifs cap {cap_str!r} for motif {motif_key!r} "
                f"is not a valid integer.",
                file=sys.stderr,
            )
            sys.exit(1)
        if cap_val <= 0:
            print(
                f"ERROR: --oversample-motifs cap for {motif_key!r} must be a positive "
                f"integer, got {cap_val}.",
                file=sys.stderr,
            )
            sys.exit(1)
        oversample_map[motif_key] = cap_val

    random.seed(args.seed)

    print(f"Streaming puzzles from: {args.puzzle_path}", flush=True)
    candidates = _stream_puzzle_csv(args.puzzle_path)

    sampled = _stratified_sample(
        candidates,
        args.samples_per_stratum,
        oversample_map=oversample_map,
        seed=args.seed,
    )
    if not sampled:
        print("ERROR: no puzzles matched any motif in MOTIF_TO_THEMES.", file=sys.stderr)
        sys.exit(1)

    train, test = _split_train_test(sampled, args.test_fraction)
    pct = 100.0 * len(test) / len(sampled) if sampled else 0.0
    print(
        f"\nTrain/test split (deterministic by PuzzleId, target {args.test_fraction:.0%} test):"
        f" {len(train)} train / {len(test)} test ({pct:.1f}% test)"
    )
    print("\nWriting fixtures:")
    _write_fixture(train, args.train_output)
    _write_fixture(test, args.test_output)


if __name__ == "__main__":
    main()
